// document.forms[0].onsubmit = function(e) {
//     e.preventDefault(); // Prevent submission
//     var password = document.getElementById("pass").value;
//     chrome.runtime.getBackgroundPage(function(bgWindow) {
//         bgWindow.setPassword(password);
//         window.close();     // Close dialog
//     });
// };

var facts =
{

	"1": "In October 25th, of 1961 there was a vote against integration of the UT athletics and Moore-Hill Hall immigration of all University dormitory facilities",
	"2": "The Malcom X Lounge received its name in 1992. This was a 10 year long process",
	"3": "In the fall of 1993 the University didnt allow minority students to practice \"stepping\" (a dancing art form) in University buildings past 10pm, even though they were previously allowed",
	"4": "The Phi Gamma Delta house had a \"no blacks allowed\" sign in their yard in 1990",
	"5": "In May of 1985, Randy Bowman, the president of the Black Student Alliance, was attacked and beaten by ttwo white men with a  pipe and a bottle.",
	"6": "On June 29th, 1985 The University Advisory Committee refused to recommend a black candidate for the Presidential selection pool",
	"7": "On February 20th of 1986 Bowman is attacked by two white men wearing Ronald Regan masks. He is held out of an eight story window in Jester dormitory",
	"8": "On December 12th of 1988: Phi Gamma Delta, also known as the \"Figis\" are criticized for the use of their Fijji island Man a Black caricature used nationally by the fraternity",
	"9": "In January of 1990: The University of Texas President, William Cunningham announces support to erect a statue of Martin Luther King Jr. after three years of silence",
	"10": "On April 3rd, 1990: Torri Luckett is elected the first African-American Student Association President. She is also the first proclaimed lesbian.",
	"12": "On April 5th: A racist display of two black track runners trailing two white runners is painted in the window of Yarings Department Store on the Drag. The display, which was sponsored by the Spooks, sparked concerns in the Black community",
	"13": "On April 6th of 1990 Racial slurs are found on the car belonging to Delta Tua Delta during the Texas Round-up parade",
	"14": "On April 7th of 1990: Phi Gamma Delta, also known as Fiji, passed out TR shirts with a Sambo caricature on the body of Michael Jordan at their basketball tournament for Texas Round up",
	"15": "On April 9th of 1990 Black Student Alliance BSA summits PRIDE (Proposed Reforms to Institute Diversity in Education). Meets with President Cunningham about racial incidents that occurred during Texas Round up festivities.",
	"16": "On April 12th of 1990 Marcus Brown, president of BSA leads an anti-racism rally on the West Mall. Afterwards , the group marched to the Fiji fraternity house to protest the racist t-shirts they passed out earlier that week.",
	"17": "April 13th of 1990: president Cunningham, who asked three Black student athletes to stand behind him, attempted to deliver a speech on the South Mall. He is untimely shouted down by protesters.",
	"18": "On April 23rd of 1990. Cunningham released an apology to the Austin American Statements but not to the student athletes about the racist activities that happened that year on campus",
	"19": "On May 16th of 1946: Harmon Marion Sweatt (1912-1982) files a lawsuit against T.S. painter, the UT president on the basis that the University of Texas School of Law violated his rights guaranteed to hum under the equal protect clause of the 14th Amendment.",
	"20": "On March 10th of 1947, the Texas Southern University was established in order to keep African Americans from attending the University of Texas School of Law",
	"21": "On June 5th of 1950, in the landmark court case Sweatt v. Painter, the Supreme court ruled that the legal education institution, Texas Southern University for Blacks was not equal in quality of that of The University of Texas School of Law.",
	"22": "In the fall of 1956 the first Black undergraduate was admitted to the University of Texas",
	"23": "In the Spring of 1962 Gwen Jordan becomes the first Black student to be elected to serve in the Student Government",
	"24": "On June 1st of 1964 Dr. Evin Perry becomes the first African American assistant professor hired by the University in the department of Engineering",
	"25": "In the Fall of 1984, The first African American studies course entitled \"The negro in American Culture\" was offered under American Studies",
	"26": "In the fall of 1970: the ethnic studies program was created",
	"27": "In the Fall of 1970 Juluiis Whitter is the first Black student to be given a scholarship to play football for the University of Texas",
	"28": "In the Spring of 1970 Ernie Haywood became the first African American Vice President in Student Government",
	"29": "In the Fall of 1980 the Texas Union closes the African American Culture room but soon reopens it due to student protests",
	"30": "In the fall of 1981: Kappa Alpha, a historically white fraternity, holds a \"slave auction\" on campus",
	"31": "On October 22nd of 1998 Students lead a Tower sit in, demanding that President Faulkner reinstate affirmative action policies not specifically prohibited by the Hopwood decision",
	"32": "On October 29th of 1998 The University of Texas President Larry Faulkner publishes a public statement in the Daily Texan regarding the student protests on October 22nd",
	"33": "In September of 1999: Racial epithets found on posters in the Malcom X lounge",
	"34": "On September 24th of 1999 the Dr Martin Luther King Jr Statue is unveiled on the East Mall",
	"35": "On march 3rd of 2000 Daron Roberts is elected as the 4th African American Student Government President",
	"36": "In April of 2000 Racist flyers are posted on campus by the National Alliance, a Neo Nazi group",
	"37": "In April of 2000 students deliver a letter with a list of demands regarding racist fliers posted on campus by the Nation Alliance, to the Office of the President",
	"38": "In Spring of 2001, students demand changes to the Center for African and African American Studies",
	"39": "In Spring of 2001 Dr Edmund T Gordon and Dr Joni Jones are appointed as director and associate Director of the Center for African and African American studies",
	"40": "In April of 2001 Black and Hispanic students are successful in stopping the Dean of Students search due to concerns of the lack of diversity in the finalist pool",
	"41": "In the Spring of 2001 the new dean oif students. Dr. Theresa Graham Brett, takes office",
	"42": "In October 31st, of 2002 the phi Gamma Delta (Fijis) host their annual Halloween party, where at least one guest attended wearing Black face",
	"43": "In January 18th of 2003: Kevin Curry is racially profiled by the University of Texas Policed Department in the Texas Union",
	"44": "On January 20th of 2003 the MLK statue is egged",
	"45": "In January 21st of 2003 the Students march to the tower and demand that President Faulkner take actions to prevent future vandalism of the statue, in addition students sponsor a 24 hour rally to protest these acts.",
	"46": "On April 6th of 1995 Blackfest 1995 takes place to celebrate Black Culture",
	"47": "In March of 1995 Student referendum passes in Student Government Association election, which called for $1 per student per semester for four years (MLK statue)",
	"48": "On June 6th a bill to allow a student fee to pay for the MLK statue passes in the Texas Legislature",
	"49": "On September 2nd of 1995 the African American Culture Committee brings Bobby Seale and Eldridge Cleaver to campus",
	"50": "On September 31st of 1995 Black men of Austin march to the capital in honor of the million man march in Washington DC",
	"51": "On December 1st of 1995 the Malcom X lounge opened",
	"52": "On December 7th of 1995 the opening ceremony for the Malcom X lounge, \"Keeping our Eyes on the Prize\" takes place",
	"53": "On April 1st of 1996, students rally against the Hopwood decision",
	"54": "On July 1st of 1996 affirmative action is ended in higher education in Texas, Mississippi, and Louisiana",
	"55": "On November 1st of 1996, the African American culture committee brings Angela Davis to the University",
	"56": "On April 1st of 1997 Marlen Whitley is elected the 3rd African American Student Government President",
	"57": "In August of 1997 4 out of 487 African American students are accepted to the University of Texas Law School",
	"58": "In September of 1997 UT Law Professor Lino Graglia, makes racist comments about Blacks and Hispanics, which sparks protests and calling for his firing",
	"59": "On September 9th of 1997, Reverend Jesse Jackson Junior comes to the University to protest the statements made by Lino Graglia",
	"60": "On September 9th of 1997 Students sponsored a 6 hour sit in at the Law School following reverend Jesse Jacksons speech",
	"61": "In 1998 on June 1st the New Multicultural Information Center Opens",
	"62": "In Fall of 1998 the Texas Attorney General Dan Morales applies a broad interpretation of the Hopwood ruling to all public universities and colleges in Texas",
	"63": "Most anthropologisits and biologists view race as a political grouping with roots in slavery and colonialism",
	"64": "Most genetic variety is not between races, but rather within races. For example, two random Italians are likely to be as genetically different as an Italian and a Chinese",
	"65": "Phernology was developed by German physician Franz Joseph Gall in 1796 and some people used it to describe the difference in races",
	"66": "Ethnicity is associated with culture, religion, language, etc. However race is a social construct associated with the idea that there are innate biological difference and has largely been discredited",
	"67": "In the early 20th century some churches in the U.S. would hang a pinewood slab on the door with a comb hanging from a string. A person could only enter if his or her skin was lighter than the pinewood and if they ould run the comb through their hair without it snagging",
	"68": "According to the 2010 American census, white and Asian children have the lowest rates of poverty of any ethnic group. Blacks had the highest level of children living in poverty at 38.2%, children who were identified with two or more races reported at 22.7% and Hispanic children were reported at 32.3%",
	"69": "Before the African slave trade boom in the 18th century, between one-half and two-thirds of all early white immigrants to the American colonies were non-free laborers. Initially, European settlers in the colonies gave blacks from Africa and Native Americans the same status as white indentured servants. By the 1700s, however, Africans and their children were treated as a different race and were viewed as life-long properties of their masters.",
	"70": "Virginia was the first state to outlaw interracial sex back in 1662. That lasted until 1967.",
	"71": "In the early 1800s, blacks hoping to move to Ohio had to post a $500 bond guaranteeing their good behavior, and they were required to produce court documents proving they were free.",
	"72": "In 2008, 46% of the people living with HIV were black, and 31.6% were white",
	"73": "Arab is not a race, but rather an epithote for someone who speaks Arabic",
	"74": "In the early 1900s eugenists attempted to use IQ tests to prove that certain races were inherently more intelligent than other races. FOr example, they used tests to try and demonstrate that blacks and recent imigrants from southern and eastern Europe were intellectually inferior to Americans of Anglo Saxon decent. By the 1940s, eugenics had been discredited both as bad science and as an excuse for racial hatred.",
	"75": "Eugenics is controlled breeding to make the ideal human. Idea brought about by a white man.",
	"76": "In the early 1900s, the Racial Integrity Act in the United States required racial classification of every person at birth and made marriage between whites and anyone with even a trace of Negro ancestry a crime. It was motivated by concern that sexual intermingling between blacks and whites would deteriorate the white race.",
	"77": "Thomas Jefferson was not only a political philosopher but also a naturalist. In one of his notes, he argued that black people were predisposed to sleeping more because their minds were empty: \“An animal whose body is at rest and who does not reflect must be disposed to sleep, of course.\”",
	"78": "The Institute of Medicine in 2002 scientifically documented widespread racial disparities in health care and suggested they stemmed at least partly from physician bias. in one generation, between 1940 and 1999, more than 4 million African Americans died prematurely relative to whites.",
	"79": "After pornography, ancestry websites are the most commonly visited on the Internet. A molecular biologist from John Hopkins asserts that each one of us has around 6.7 billion relatives.",
	"80": "White men and asain women pairings are the most common form of interracial dating and marriage in the United States",
	"81": "Research indicates that infacts as young as six months old notice racial differences",
	"82": "Statistics show that white wife/black husband marriages are twice as likely to end in divorce than white wife/white husband couples by the 10th year of marriage. However, a black wife/white husband marriage is 44 percent less likely to divorce than a white wife and white husband couple by the 10th year of marriage.",
	"83": "According to federal statistics one in four students reports being a target of ethnic or racial bias in a typical school year",
	"84": "In California, 40 percent of African American men between 18-25 are either in jail, on parole, or on probation",
	"85": "Sociologists Simon Cheng and Brian Powell found that parents in biracial families typically devote more time and money to enrolling their kids in activities, such as music lessons and museum trips—not necessarily because they have more money, but most likely to compensate for their marginalized social status",
	"86": "California was the first state to ban the use of race and ethnicity in public university admissions. However, now that affirmative action is banned (Proposition 209), Asian American students have dominated admissions. At UC Berkeley, for example, 46% of those admitted into the 2012 freshman class are Asian; 30% are white.",
	"87": "﻿ Black students accounted for 18 percent of the country\’s pre-K enrollment, but made up 48 percent of preschoolers with multiple out-of-school suspensions.",
	"88": "During the 2011-2012 school year ﻿ Black students were expelled at three times the rate of white students.",
	"89": "﻿During the 2011-2012 school year American Indian and Native-Alaskan students represented less than 1 percent of students, but 3 percent of expulsions.",
	"90": "During the 2011-2012 school year ﻿ Black girls were suspended at higher rates than all other girls and most boys.",
	"91": "During the 2011-2012 school year ﻿ A quarter of the schools with the highest percentage of black and Latino students did not offer Algebra II",
	"92": "During the 2011-2012 school year ﻿ Black and Latino students accounted for 40 percent of enrollment at schools with gifted programs, but only represented 26 percent of students in such programs",
	"93": "During the 2011-2012 school year ﻿ Black, Latino and Native American students attended schools with higher concentrations of first-year teachers (3 to 4 percent) than white students (1 percent)",
	"94": "During the 2011-2012 school year ﻿ Black students were more than three times as likely to attend schools where fewer than 60 percent of teachers meet all state certification and licensure requirements.",
	"95": "40 percent of all bottled water sold in the world is bottled tap water",
	"96": "27,000 trees are felled each day for toilet paper",
	"97": "Paper can be recycled only six times. After that, the fibers are too weak to hold together.",
	"98": "There is no known scientific way of predicting earthquakes. The most reliable method is to count the number of missing cats in the local paper: if it trebles, an earthquake is imminent",
	"99": "Rainforests are being cut down at the rate of 100 acres per minute",
	"100": "More than 20,000,000 Hershey\'s Kisses are wrapped each day, using 133 square miles of tinfoil. All that foil is recyclable",
	"101": "The U.S. is the #1 trash-producing country in the world at 1,609 pounds per person per year. This means that 5% of the world\'s people generate 40% of the world\'s waste. We toss out two billion plastic razors, a million and a half tons of paper towels, and 12 billion disposable diapers annually",
	"102": "On average, ONE supermarket goes through 60,500,000 paper bags per year!",
	"103": "Every day over 40,000 children die from preventable diseases",
	"104": "Nuclear power releases much less radiation into the environment than the currently most used source of electricity (coal)",
	"105": "While deployed in Afghanistan or Iraq, American female soldiers were more likely to be raped by their fellow soldier than attacked by the enemy.",
	"106": "1 in 6 men have experienced abusive sexual experiences before age 18 and this figure is probably on the low end as males who have such experiences are less likely to disclose them than woman are",
	"107": "40% of drinking water comes from plastic bottles.",	
}

var random = Math.floor((Math.random() * 107) + 1);
var questionDiv = document.getElementById('question');
var factSpan = questionDiv.querySelector('.factsText');
factSpan.innerHTML = facts[random];
console.log(facts[random]);